### ISSUE TITLE
Inconsistent PWM

### ISSUE THREAD

**Issue by sdaitzman** [NextThingCo/PocketCHIP-PCB#2]
![img_6297](https://cloud.githubusercontent.com/assets/1499476/22253174/942d7f4e-e21e-11e6-9a6a-9fd6afac8c69.jpg)
The PWM output on my C.H.I.P. is extremely strange. It has strange up and down spikes each cycle.

My sourcecode is at https://github.com/sdaitzman/chip-io-test

@alleybeachelectric @Flexshot

**Comment by blinkengus** [comment]
Hi, this is not a PocketCHIP PCB issue. Please post it in the CHIP-IO repo: https://github.com/xtacocorex/CHIP_IO

**Comment by sdaitzman** [comment]
@blinkengus actually, I used a different software package and (unless that package had an issue) this would very likely be a hardware-level problem.

**Comment by blinkengus** [comment]
@sdaitzman my mistake, if you're pulling in the Node CHIP IO software, you'll want to put that ticket here: https://github.com/sandeepmistry/node-chip-io

At the hardware level, those pins are coming directly from the R8 die (through a couple solder joints) and I would suspect any halting, drag or draw on their duty cycle is caused by their handling from within Linux.
